robot_id: "0"
robot_name: "robot0"
map_frame_id: "robot0/map"
sensor_frame_id: "camera_color_optical_frame"
robot_base_frame_id: "robot0/Local"
track_point_frame_id: "camera_link"
robot_pose_with_covariance_topic: "/camera_link_pose"
robot_pose_cache_size: 200
robot_local_map_size: 50
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
octomap_resolution: 0.02
map_saving_file: "./map.pcd"
submap_saving_dir: "./submaps/"
camera_params_yaml: "/home/hesuqin/zju_elevation_map_ws/src/GEM/elevation_mapping/yq_intrinsic.yaml"
orthomosaic_saving_dir: "./image/"
