robot_id: "0"
robot_name: "robot0"
map_frame_id: "t265_odom_frame"
sensor_frame_id: "d455_color_optical_frame"
robot_base_frame_id: "t265_pose_frame"
track_point_frame_id: "d455_link"
robot_pose_with_covariance_topic: "/d455_link_pose"
robot_pose_cache_size: 200
robot_local_map_size: 100
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
octomap_resolution: 0.03
map_saving_file: "./map.pcd"
submap_saving_dir: "./submaps/"
camera_params_yaml: "/home/hesuqin/realsense_elevation_mapping/src/realsense_elevation_mapping/GEM/elevation_mapping/yq_intrinsic.yaml"
orthomosaic_saving_dir: "./image/"
